### ISSUE TITLE
Not able to install it in ubuntu .

### ISSUE THREAD

**Issue by rishavpathania1995** [inovex/mqtt-stresser#8] opened 2018-06-08 06:10 UTC
root@ip-172-31-22-25:~/mqtttester/mqtt-stresser# make
GOOS=windows GOARCH=amd64 go build -o build/mqtt-stresser.exe
/bin/sh: 1: go: not found
Makefile:46: recipe for target 'build/mqtt-stresser-windows-amd64.zip' failed
make: *** [build/mqtt-stresser-windows-amd64.zip] Error 127

**Comment by rishavpathania1995** [comment] 2018-06-08 06:11
root@ip-172-31-22-25:~/mqtttester/mqtt-stresser# make
GOOS=windows GOARCH=amd64 go build -o build/mqtt-stresser.exe
/bin/sh: 1: go: not found
Makefile:46: recipe for target 'build/mqtt-stresser-windows-amd64.zip' failed
make: *** [build/mqtt-stresser-windows-amd64.zip] Error 127

**Comment by invadersmustdie** [comment] 2018-06-08 08:53
`/bin/sh: 1: go: not found` <- looks like the build is unable to find the go binary. Can you please check your host system and verify that go is placed in $PATH

As this is not a bug. I'm closing this issue

**Closed by invadersmustdie** 2018-06-08 08:53 UTC
