### ISSUE TITLE
no such file or directory error

### ISSUE THREAD

**Issue by pineli** [inovex/mqtt-stresser#36] opened 2020-07-02 22:37 UTC
I`m with problem to execute mqtt-stresser. I already updated the modules

```sh
./build/mqtt-stresser-linux-amd64 -broker tcp://localhost:1883 -num-clients 100 -num-messages 150 -rampup-delay 1s -rampup-size 10 -global-timeout 180s -timeout 20s
open : no such file or directory
```

**Comment by arnisoph** [comment] 2020-07-03 11:16
Interesting. The binary is marked as executable? (`chmod +x`) You have chosen the correct binary for your platform?

**Comment by jsponz** [comment] 2020-07-07 19:30
Same here :-(

**Comment by hikhvar** [comment] 2020-07-07 20:35
Can you give us some details about your systems? Where did you get the binary from? Build yourself or latest release? What operating system are you using? Do you run alpine Linux or any other distribution using muslc instead of glibc?

**Comment by jsponz** [comment] 2020-07-07 20:47
I built it using your instructions. I am using a fresh installation of Ubuntu. What else do you need?

**Comment by arnisoph** [comment] 2020-07-07 21:12
I also had issues with the non-static linux amd64 binary (CGO). Might be a problem with the binary itself. We'll have a look tomorrow. In the mean time please try the static binary (CGO disabled) or https://github.com/inovex/mqtt-stresser/releases/tag/v4 (fresh release)?

**Comment by jsponz** [comment] 2020-07-08 05:28
Same result evne with the fresh release

**Comment by arnisoph** [comment] 2020-07-08 06:46
with both linux-amd64 binaries?

**Comment by jsponz** [comment] 2020-07-08 06:46
Yes...

**Comment by arnisoph** [comment] 2020-07-09 07:37
@jsponz @pineli would you please try out the latest pre/beta release?

https://github.com/inovex/mqtt-stresser/releases/tag/v5-beta1

**Comment by jsponz** [comment] 2020-07-09 15:40
Same result? 

![image](https://user-images.githubusercontent.com/12778286/87060805-3c47f900-c20b-11ea-88f1-ac37ae2a2dc0.png)

**Comment by arnisoph** [comment] 2020-07-10 07:13
Going through the code I can't find any occurrences that would generate such an error (string). Did you ensure using the latest beta release v5-beta1?

https://github.com/inovex/mqtt-stresser/releases/tag/v5-beta1

**Comment by jsponz** [comment] 2020-07-10 07:17
Yes, I have followed your indications... 

![image](https://user-images.githubusercontent.com/12778286/87127384-1d3e7b00-c28e-11ea-82b5-14bc5aefaf9f.png)

**Comment by arnisoph** [comment] 2020-07-10 07:25
hmm. strange. Do you experience the same with other endpoints such as tcp://broker.mqttdashboard.com:1883 or another local broker instance?

![image](https://user-images.githubusercontent.com/1507504/87128082-50cdd500-c28f-11ea-9a74-f22fa6c9a0de.png)

**Comment by hikhvar** [comment] 2020-07-10 12:11
> Yes, I have followed your indications...
> 
> ![image](https://user-images.githubusercontent.com/12778286/87127384-1d3e7b00-c28e-11ea-82b5-14bc5aefaf9f.png)

In your previous comment you ran the stresser as root on the computer `panel` could you please download the binary there, make it executabe and run your initial test?

**Comment by arnisoph** [comment] 2020-07-14 12:55
@pineli  are you still able to reproduce the issue with the latest binary (v5-beta1)?

**Comment by hikhvar** [comment] 2020-07-27 11:26
Since neither me nor @arnisoph able to reproduce the bug with the latest build, I close this issue. If you still have problems with the latest release, feel free to reopen this issue.

**Closed by hikhvar** 2020-07-27 11:26 UTC
Labels: bug
